### PR TITLE
[Bug fixed]remove __init__.py files and update README

### LINKED ISSUE #1: ModuleNotFoundError: No module named 'perceval.backend'
This error is raised when the backend is used with perceval because it doesn't follows the [PEP 420](https://peps.python.org/pep-0420/) about namespaces.

```
    from perceval.backend import find_signature_parameters, Archive
ModuleNotFoundError: No module named 'perceval.backend'
```

To fix it, you should remove `__init__.py` files of `perceval` and `perceval.backends` packages.

### PR DESCRIPTION
**Pull request by shanchenqi**
This pull request is committed to fix https://github.com/chaoss/grimoirelab-perceval-gitee/issues/1.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
LGTM but, would you mind to squash the commits in one, so we can have a clean history? Don't forget also to sign off the commits.

**Comment by eyehwan** [comment]
Yes, I think we need to follow the contribution guideline in the future work. https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#accepting-contributions

**Comment by shanchenqi** [comment]
OK, Thank you @sduenas and @eyehwan, I have updated the commit messages. Could you help me to review it again?

**Review by eyehwan — APPROVED** [review]
lgtm

**Pull request merged**
